// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconGg:menuLeftAlt': typeof import('~icons/gg/menu-left-alt')['default']
    'IconHeroicons:trash': typeof import('~icons/heroicons/trash')['default']
    'IconHumbleicons:pencil': typeof import('~icons/humbleicons/pencil')['default']
    'IconIc:baselineFilterAlt': typeof import('~icons/ic/baseline-filter-alt')['default']
    'IconIc:outlineAddShoppingCart': typeof import('~icons/ic/outline-add-shopping-cart')['default']
    'IconIc:roundCheckCircle': typeof import('~icons/ic/round-check-circle')['default']
    'IconIc:roundFilterList': typeof import('~icons/ic/round-filter-list')['default']
    'IconIc:roundKeyboardArrowDown': typeof import('~icons/ic/round-keyboard-arrow-down')['default']
    'IconIc:roundKeyboardArrowRight': typeof import('~icons/ic/round-keyboard-arrow-right')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconLucide:users': typeof import('~icons/lucide/users')['default']
    'IconMajesticons:doorExit': typeof import('~icons/majesticons/door-exit')['default']
    'IconMaterialSymbols:addCircleOutlineRounded': typeof import('~icons/material-symbols/add-circle-outline-rounded')['default']
    'IconMaterialSymbols:addCircleRounded': typeof import('~icons/material-symbols/add-circle-rounded')['default']
    'IconMaterialSymbols:addPhotoAlternate': typeof import('~icons/material-symbols/add-photo-alternate')['default']
    'IconMaterialSymbols:arrowBackIosRounded': typeof import('~icons/material-symbols/arrow-back-ios-rounded')['default']
    'IconMaterialSymbols:checkCircle': typeof import('~icons/material-symbols/check-circle')['default']
    'IconMaterialSymbols:checkCircleRounded': typeof import('~icons/material-symbols/check-circle-rounded')['default']
    'IconMaterialSymbols:keyboardArrowDownRounded': typeof import('~icons/material-symbols/keyboard-arrow-down-rounded')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMi:userAdd': typeof import('~icons/mi/user-add')['default']
    'IconMingcute:closeCircleLine': typeof import('~icons/mingcute/close-circle-line')['default']
    'IconMingcute:closeFill': typeof import('~icons/mingcute/close-fill')['default']
    'IconMingcute:upload3Fill': typeof import('~icons/mingcute/upload3-fill')['default']
    'IconOcticon:trash16': typeof import('~icons/octicon/trash16')['default']
    'IconRi:eye2Line': typeof import('~icons/ri/eye2-line')['default']
    'IconRi:search2Line': typeof import('~icons/ri/search2-line')['default']
    'IconRi:shoppingBasketLine': typeof import('~icons/ri/shopping-basket-line')['default']
    'IconSimpleLineIcons:optionsVertical': typeof import('~icons/simple-line-icons/options-vertical')['default']
    'IconTypcn:tick': typeof import('~icons/typcn/tick')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconWpf:fullTrash': typeof import('~icons/wpf/full-trash')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
